apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: dev
  labels:
    role: demo1
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  serviceAccountName: dev