apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-retain
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: azure_storage_account_name