apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customclasspvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-retain
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 5Gi