apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxrs
spec:
  replicas: 2
  selector:
    matchLabels:
      role: demo2
  template:
    metadata:
      labels:
        role: demo2
    spec:
      containers:
      - name: nginx
        image: nginx
