apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: cloudcomputing
  automountServiceAccountToken: true
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP