apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: dev
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"