apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      serviceAccount: demo
      containers:
      - image: kammana/nodeapp:v2
        name: nodeapp
        ports:
        - containerPort: 8080
