apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-storage
  labels:
    usage: catphotosapp1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: demo
    readOnly: false