kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-access
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user-full-access
subjects:
# - kind: Group
#   namespace: dev
#   name: 396bc686-f09b-45c5-8f44-53b5861faa51
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: kethan@devopsbychandu3.onmicrosoft.com
# - kind: ServiceAccount
#   name: <sa Name>
#   namespace: dev