---
- name: apache2
  hosts: webserver
  remote_user: root
  become: true
  tasks:
    - name: install apache2
      apt:
        name:  apache2
        state: latest
        update_cache: yes
    - name: running apache2
      service:
        name: apache2
        state: started
    - name: create content
      copy:
        content:  "hello World"
        dest: /var/www/html/index.html