apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    name: mypod2
    volumeMounts:
      - name: emptydir
        mountPath: /mnt/emptydir
  volumes:
  - name: emptydir
    emptyDir: {}