apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: capacity
            operator: In
            values:
            - high-memory1
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:2.0